source: src
destination: _site

collections:
  boards:
    output: true

defaults:
  - scope:
      path: ""
      type: boards
    values:
      layout: board

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules"]
exclude:
  - package.json
  - yarn.lock

baseurl: "/scorecard"
