services:
  - title: Health Care
    page_path_filter: regex:www.va.gov/health-care
    tools:
      - title: Apply for Health care benefits
        page_path_filter: 'regex: /health-care/apply'
        event_category_filter: 'regex: "Transactions"'
        event_action_filter: 'regex: "Forms"'
  - title: Education
    page_path_filter: regex:www.va.gov/(gi-bill|education)
    tools:
      - title: 'GI Bill comparison tool: Transactions'
        page_path_filter: 'regex:/gi-bill-comparison-tool'