name: "Test and Build"

on: [push, workflow_dispatch]

jobs:
  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: run unit tests
      run: make ci-unit-test
    - name: run integration tests
      env:
        GA_SERVICEACCOUNT: ${{ secrets.GA_SERVICEACCOUNT }}
        FORESEE_CREDENTIALS: ${{ secrets.FORESEE_CREDENTIALS }}
      run: make integration-test

  build:
    name: Build
    runs-on: ubuntu-latest
    container: jekyll/jekyll:4.0
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: set up node
      uses: actions/setup-node@master
      with:
        node-version: '12.20.1'
    - name: install correct yarn version
      run: npm install --global --force yarn@1.22.0
    - name: install dependencies
      run: make yarn-install
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TW_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TW_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: fetch data from s3
      run: |
        aws s3 cp src/_data s3://va-performance-dashboard-data/ --recursive
    - name: build
      run: /usr/gem/bin/jekyll build --trace
    - name: upload jekyll site
      uses: actions/upload-artifact@v2
      with:
        name: _site
        path: _site

  ui-test:
    name: UI Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: download jekyll site
      uses: actions/download-artifact@v2
    - name: run ui tests
      uses: ./.github/actions/ui-test-docker-action