name: "Data update"

on: push
#  schedule:
#    - cron: '0 2 * * *'

jobs:
  refresh-data:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: github-actions
      - name: fetch data
        env:
          GA_SERVICEACCOUNT: ${{ secrets.GA_SERVICEACCOUNT }}
          FORESEE_CREDENTIALS: ${{ secrets.FORESEE_CREDENTIALS }}
        working-directory: ./scripts
        run: ./fetch-data-docker-wrapper.sh
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Copy data to s3
        run: |
          aws s3 sync src/_data s3://va-performance-dashboard-data/data
      - name: trigger build workflow
        uses: ./.github/actions/trigger-workflow-action
        with:
          workflow: test-build-deploy
          token: ${{ secrets.PERSONAL_TOKEN }}
