name: "Data update"

on:
  push:
    paths:
    - 'scripts/**'
    branches:
      - developement
      - github-actions
  schedule:
    - cron: '0 2 * * *'

jobs:
  refresh-data:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: github-actions
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: marvinpinto/action-inject-ssm-secrets@29c7bcaeb95b662ddf9dacb4f2127ecd2286f63b
        with:
          ssm_parameter: "/performance-dashboard/foresee-credentials"
          env_variable_name: "FORESEE_CREDENTIALS"
      - name: fetch data
        env:
          GA_SERVICEACCOUNT: ${{ env.GA_SERVICEACCOUNT }}
          FORESEE_CREDENTIALS: ${{ env.FORESEE_CREDENTIALS }}
        working-directory: ./scripts
        run: |
          GA_SERVICEACCOUNT=$(aws ssm get-parameter  --with-decrypt --name '/performance-dashboard/ga-serviceaccount' | jq '.Parameter.Value' -r)
          ./fetch-data-docker-wrapper.sh
      - name: Copy data to prod s3 bucket if we're on master
        if: ${{ github.ref == 'refs/heads/github-actions' }}
        run: aws s3 sync src/_data s3://va-performance-dashboard-data/data
#        run: aws s3 sync src/_data s3://va-performance-dashboard-data-prod/data
      - name: Copy data to dev s3 bucket if we're in development mode
        if: ${{ github.ref == 'refs/heads/development' }}
        run: aws s3 sync src/_data s3://va-performance-dashboard-data/data
#        run: aws s3 sync src/_data s3://va-performance-dashboard-data-dev/data
      - uses: marvinpinto/action-inject-ssm-secrets@29c7bcaeb95b662ddf9dacb4f2127ecd2286f63b
        with:
          ssm_parameter: "/performance-dashboard/github-access-token"
          env_variable_name: "PERSONAL_TOKEN"
      - name: trigger build workflow
        uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7
        with:
          workflow: test-build-deploy.yml
          token: ${{ env.PERSONAL_TOKEN }}
