name: "test-build-deploy"

on:
  push:
    paths-ignore:
      - 'scripts/**'
  workflow_dispatch:

jobs:
  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: run unit tests
      run: make ci-unit-test
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-gov-west-1
    - uses: marvinpinto/action-inject-ssm-secrets@29c7bcaeb95b662ddf9dacb4f2127ecd2286f63b
      with:
        ssm_parameter: "/dsva-vagov/performance_dashboard/foresee_credentials"
        env_variable_name: "FORESEE_CREDENTIALS"
    - name: run integration tests
      run: |
        export GA_SERVICEACCOUNT=$(aws ssm get-parameter  --with-decrypt --name '/dsva-vagov/performance_dashboard/ga_serviceaccount' | jq '.Parameter.Value' -r)
        make integration-test

  fetch-data:
    name: Fetch Data from S3
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-gov-west-1
    - name: fetch data from s3 dev bucket
      if: ${{ github.ref == 'refs/heads/development' }}
      run: aws s3 cp s3://dsva-vetsgov-scorecard-dev/data src/_data --recursive
    - name: fetch data from s3 prod bucket
      if: ${{ github.ref == 'refs/heads/master' }}
      run: aws s3 cp s3://dsva-vetsgov-scorecard-prod/data src/_data --recursive
    - name: upload data
      uses: actions/upload-artifact@v2
      with:
        name: _data
        path: src/_data

  build:
    name: Jekyll Site Build
    needs: fetch-data
    runs-on: ubuntu-latest
    container: jekyll/jekyll:4.0
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: download data
      uses: actions/download-artifact@v2
      with:
        name: _data
        path: src/_data
    - name: set up node
      uses: actions/setup-node@master
      with:
        node-version: '12.20.1'
    - name: install correct yarn version
      run: npm install --global --force yarn@1.22.0
    - name: install dependencies
      run: make yarn-install
    - name: build
      run: /usr/gem/bin/jekyll build --trace
    - name: upload jekyll site
      uses: actions/upload-artifact@v2
      with:
        name: _site
        path: _site

  ui-test:
    name: UI Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: download jekyll site
      uses: actions/download-artifact@v2
    - name: run ui tests
      uses: ./.github/actions/ui-test-docker-action

  dev-deploy:
    name: Jekyll Site Deployment
    needs: [ ui-test, test]
    if: ${{ github.ref == 'refs/heads/development' }}
    runs-on: ubuntu-latest
    steps:
    - name: download jekyll site
      uses: actions/download-artifact@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-gov-west-1
    - name: upload site to S3
      run: aws s3 sync --acl public-read _site s3://dsva-vetsgov-scorecard-dev --exclude "data/*"

  staging-deploy:
    name: Jekyll Site Deployment
    needs: [ ui-test, test ]
    runs-on: ubuntu-latest
    steps:
    - name: download jekyll site
      uses: actions/download-artifact@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-gov-west-1
    - name: upload site to S3
      run: aws s3 sync --acl public-read _site s3://dsva-vetsgov-scorecard-staging

  prod-deploy:
    name: Jekyll Site Deployment
    needs: [ ui-test, test ]
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: download jekyll site
        uses: actions/download-artifact@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
      - name: upload site to S3
        run: aws s3 sync --acl public-read _site s3://dsva-vetsgov-scorecard-prod --exclude "data/*"
