name: "Daily Data Refresh Trigger"

on:
  push:
    tags:
    - 'data-refresh'
  schedule:
    - cron: '5 3 * * *'

jobs:
  trigger-data-refresh:
    name: Trigger Data Refresh
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
      - uses: marvinpinto/action-inject-ssm-secrets@29c7bcaeb95b662ddf9dacb4f2127ecd2286f63b
        with:
          ssm_parameter: "/dsva-vagov/performance_dashboard/github_access_token"
          env_variable_name: "PERSONAL_TOKEN"
      - name: trigger build workflow
        uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7
        with:
          workflow: Data-Refresh
          token: ${{ env.PERSONAL_TOKEN }}
          ref: refs/heads/master